[package]
name = "minusagent"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
async-trait = "0.1"
reqwest = { version = "0.13.1", features = ["json"] }
serde_json = "1.0.149"
tokio = "1.49.0"

[dev-dependencies]
dotenvy = "0.15.7"
tokio = { version = "1.49.0", features = ["rt-multi-thread", "macros"] }
